# -*- coding: utf-8 -*-
"""Isaac_Espinosa_Deber1_IA_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MApQbNNGA6UU0zvDhYaiA1kshe0kACQ3
"""

start=(2,4,3,1,0,6,7,5,8)
goal=(1,2,3,4,5,6,7,8,0)


def print_board(state):
  i=0
  while i<9:
    row= state[i:i+3]
    line=""
    for value in row:
      if value ==0:
        line=line+ "_ "
      else:
        line=line+ str(value)+" "
    print(line)
    i=i+3
  print("")

def get_successors(state):
  blank = state.index(0)
  row=blank//3
  col=blank%3

  move_indexes= []
  if row >0:
    move_indexes.append(blank-3)
  if row <2:
    move_indexes.append(blank+3)
  if col >0:
    move_indexes.append(blank-1)
  if col <2:
    move_indexes.append(blank+1)

  successors=[]
  for new_index in move_indexes:
    new_state=list(state)
    new_state[blank]=state[new_index]
    new_state[new_index]=0
    successors.append(tuple(new_state))
  return successors

def bfs(start,goal):
  queue=[[start]]
  visited=set()
  visited.add(start)
  states_generated=1

  while len(queue)>0:
    path=queue.pop(0)
    current=path[-1]

    if current==goal:
      return path,states_generated

    successors=get_successors(current)
    for next_state in successors:
      if next_state not in visited:
        visited.add(next_state)
        states_generated=states_generated+1
        new_path=path+[next_state]
        queue.append(new_path)

  return None, states_generated

def dfs(start,goal,max_depth):
  stack=[[start]]
  visited=set()
  visited.add(start)
  states_generated=1

  while len(stack)>0:
    path=stack.pop()
    current=path[-1]

    if current==goal:
      return path,states_generated

    if len(path)-1<max_depth:
      successors=get_successors(current)
      for next_state in successors:
        if next_state not in visited:
          visited.add(next_state)
          states_generated=states_generated+1
          new_path=path +[next_state]
          stack.append(new_path)

  return None, states_generated

def get_position(value,state):
  index=state.index(value)
  row=index//3
  col=index%3
  return row,col

def manhattan_distance(state,goal):
  total=0
  value=1
  while value <= 8:
    row1,col1=get_position(value,state)
    row2,col2=get_position(value,goal)
    total=total+abs(row1-row2)+abs(col1-col2)
    value=value+1
  return total


def euclidean_distance(state,goal):
  total=0.0
  value=1
  while value <=8:
    row1,col1=get_position(value,state)
    row2,col2=get_position(value,goal)
    squared_distance=(row1-row2)**2 + (col1-col2)**2
    total=total+squared_distance ** 0.5
    value=value+1
  return total


def misplaced_tiles(state,goal):
  total=0
  i=0
  while i<9:
    if state[i]!=0 and state[i]!= goal[i]:
      total=total+1
    i=i+1
  return total

def best_fs(start,goal,heuristic):
  queue=[[start]]
  visited=set()
  visited.add(start)
  states_generated=1

  while len(queue)>0:
    best_index=0
    best_value=heuristic(queue[0][-1],goal)
    i=1
    while i<len(queue):
      value=heuristic(queue[i][-1],goal)
      if value<best_value:
        best_index=i
        best_value=value
      i=i+1

    path=queue.pop(best_index)
    current=path[-1]

    if current == goal:
      return path, states_generated

    successors =get_successors(current)
    for next_state in successors:
      if next_state not in visited:
        visited.add(next_state)
        states_generated=states_generated+1
        new_path=path+[next_state]
        queue.append(new_path)

  return None, states_generated

def show_result(name,path,states_generated):
  print("----- "+name+" -----")
  if path is None:
    print("No solution found.")
    print("")
    return

  print("moves to reach the goal: ", len(path)-1)
  print("states generated: ", states_generated )
  print("states analyzed(path length): ",len(path))
  print("")

  step=0
  while step<len(path):
    print("step",step,":")
    print_board(path[step])
    step=step+1

def main():
  print("start point: ")
  print_board(start)
  print("goal point: ")
  print_board(goal)

  path,states_generated=bfs(start,goal)
  show_result("bfs",path,states_generated)

  path,states_generated=dfs(start,goal,10)
  show_result("dfs",path,states_generated)

  path,states_generated=best_fs(start,goal,manhattan_distance)
  show_result("best_fs_manhattan",path,states_generated)

  path,states_generated=best_fs(start,goal,euclidean_distance)
  show_result("best_fs_euclidean",path,states_generated)

  path,states_generated=best_fs(start,goal,misplaced_tiles)
  show_result("best_fs_misplaced",path,states_generated)

main()

N = 9



cuadrantes_inicio = [
    ('A', 'B', 'C'),
    ('D', 'E', 'F'),
    ('G', 'H', 'I')
]


cuadrantes_final = [
    ('A', 'B', 'C'),
    ('H', 'I', 'D'),
    ('G', 'F', 'E')
]


patron_inicio = [
    ('1', '2', '3'),
    ('4', '5', '6'),
    ('7', '8', '9')
]


patron_final = [
    ('1', '2', '3'),
    ('8', '9', '4'),
    ('7', '6', '5')
]


def construir_tablero(cuadrantes, patron):


    tablero = [None] * (N * N)

    for fila_cuadrante in range(3):
        for col_cuadrante in range(3):

            letra = cuadrantes[fila_cuadrante][col_cuadrante]

            for r in range(3):
                for c in range(3):

                    numero = patron[r][c]
                    ficha = numero + letra

                    fila = fila_cuadrante * 3 + r
                    col = col_cuadrante * 3 + c

                    pos = fila * N + col

                    if ficha == "9I":

                        tablero[pos] = None
                    else:
                        tablero[pos] = ficha

    return tablero


tablero_inicial = tuple(
    construir_tablero(cuadrantes_inicio, patron_inicio)
)

tablero_meta = tuple(
    construir_tablero(cuadrantes_final, patron_final)
)


def imprimir_tablero(tablero):
    for fila in range(N):

        linea = ""

        for col in range(N):

            ficha = tablero[fila * N + col]

            if ficha is None:
                ficha = "--"

            linea += ficha.rjust(4)

        print(linea)

    print()




def encontrar_hueco(tablero):
    return tablero.index(None)


def generar_vecinos(tablero):



    vecinos = []

    pos = encontrar_hueco(tablero)

    fila = pos // N
    col = pos % N

    movimientos = [
        (-1, 0, "arriba"),
        (1, 0, "abajo"),
        (0, -1, "izquierda"),
        (0, 1, "derecha")
    ]

    for df, dc, nombre in movimientos:

        nf = fila + df
        nc = col + dc

        if 0 <= nf < N and 0 <= nc < N:

            nueva_pos = nf * N + nc

            nuevo_tablero = list(tablero)


            nuevo_tablero[pos], nuevo_tablero[nueva_pos] = (
                nuevo_tablero[nueva_pos],
                nuevo_tablero[pos]
            )

            vecinos.append(
                (tuple(nuevo_tablero), nombre)
            )

    return vecinos




posicion_meta = {}

for i, ficha in enumerate(tablero_meta):

    if ficha is not None:
        posicion_meta[ficha] = (i // N, i % N)


def heuristica_manhattan(tablero):

    total = 0

    for i, ficha in enumerate(tablero):

        if ficha is None:
            continue

        fila_actual = i // N
        col_actual = i % N

        fila_meta, col_meta = posicion_meta[ficha]

        total += (
            abs(fila_actual - fila_meta)
            + abs(col_actual - col_meta)
        )

    return total




def resolver_80_tile():



    nodo_inicial = [
        heuristica_manhattan(tablero_inicial),
        tablero_inicial,
        []
    ]

    frontera = [nodo_inicial]

    visitados = set()
    visitados.add(tablero_inicial)

    estados_generados = 1
    estados_analizados = 0


    arbol_explorado = []

    while frontera:


        mejor_indice = 0

        for i in range(1, len(frontera)):

            if frontera[i][0] < frontera[mejor_indice][0]:
                mejor_indice = i

        h_actual, tablero_actual, camino_actual = frontera.pop(
            mejor_indice
        )

        estados_analizados += 1

        if len(arbol_explorado) < 20:

            arbol_explorado.append(
                (
                    tablero_actual,
                    h_actual,
                    len(camino_actual)
                )
            )

        if estados_analizados % 5000 == 0:

            print(
                "...",
                estados_analizados,
                "estados analizados. Mejor heuristica ahora:",
                h_actual
            )


        if tablero_actual == tablero_meta:

            return (
                camino_actual,
                estados_generados,
                estados_analizados,
                arbol_explorado
            )


        for vecino, nombre_movimiento in generar_vecinos(
            tablero_actual
        ):

            if vecino not in visitados:

                visitados.add(vecino)

                h_vecino = heuristica_manhattan(vecino)

                nuevo_camino = camino_actual + [
                    nombre_movimiento
                ]

                frontera.append(
                    [
                        h_vecino,
                        vecino,
                        nuevo_camino
                    ]
                )

                estados_generados += 1

    return (
        None,
        estados_generados,
        estados_analizados,
        arbol_explorado
    )




if __name__ == "__main__":

    print("Tablero inicial:")
    imprimir_tablero(tablero_inicial)

    print("Tablero meta:")
    imprimir_tablero(tablero_meta)

    print("Buscando solucion,")
    print("esto puede tardar mucho...")
    print("(Ctrl+C para detener)")
    print()

    camino = None
    generados = 0
    analizados = 0
    arbol = []

    try:

        (
            camino,
            generados,
            analizados,
            arbol
        ) = resolver_80_tile()

    except KeyboardInterrupt:

        print()
        print("Busqueda interrumpida por el usuario.")

    print()
    print("--- Resultados ---")

    print("Estados generados:", generados)
    print("Estados analizados:", analizados)

    if camino is not None:

        print(
            "Longitud del camino encontrado:",
            len(camino)
        )

        print("Movimientos:", camino)

    else:

        print(
            "Todavia no se encontro una solucion "
            "(o se interrumpio antes de encontrarla)."
        )

    print()
    print(
        "--- Muestra del arbol explorado "
        "(primeros nodos analizados) ---"
    )

    for idx, (tablero, h, profundidad) in enumerate(
        arbol
    ):

        print(
            "Nodo",
            idx,
            "profundidad =",
            profundidad,
            "heuristica =",
            h
        )

        if idx < 3:
            imprimir_tablero(tablero)

def validate(chessboard,row,column):
  for i in range (column):
    if chessboard[i]==row:
      return False

    if abs(chessboard[i]-row)==abs(i-column):
      return False

  return True

def solve(chessboard,column,n):
  if column==n:
    return True
  for row in range(n):
    if validate(chessboard,row,column):
      chessboard[column]=row
      if solve(chessboard,column+1,n):
        return True
  return False

def prnt(chessboard,n):
  for row in range(n):
    for column in range(n):
      if chessboard[column]==row:
        print("1",end=" ")
      else:
        print("0",end=" ")
    print()

n=int(input("dimensions of the chessboard: "))

chessboard=[0]*n
if solve(chessboard,0,n):
  print("\nSolution:")
  prnt(chessboard,n)
else:
  print("No solution")

start=(0,0,0,0)
goal=(1,1,1,1)
def safe(state):
  farmer=state[0]
  wolf=state[1]
  goat=state[2]
  cabbage=state[3]

  if wolf==goat and farmer != wolf:
    return False
  if goat==cabbage and farmer != goat:
    return False
  return True


def get_successors(state):
  farmer=state[0]
  wolf=state[1]
  goat=state[2]
  cabbage=state[3]
  other_side=1-farmer
  successors=[]

  new_state=(other_side,wolf,goat,cabbage)
  if safe(new_state):
    successors.append(new_state)

  if wolf==farmer:
    new_state=(other_side,other_side,goat,cabbage)
    if safe(new_state):
      successors.append(new_state)

  if goat==farmer:
    new_state=(other_side,wolf,other_side,cabbage)
    if safe(new_state):
      successors.append(new_state)

  if cabbage==farmer:
    new_state=(other_side,wolf,goat,other_side)
    if safe(new_state):
      successors.append(new_state)

  return successors

def bfs(start,goal):
  queue=[[start]]
  visited=[start]

  while len(queue)>0:
    path=queue.pop(0)
    current=path[-1]

    if current==goal:
      return path

    successors= get_successors(current)
    for next_state in successors:
      if next_state not in visited:
        visited.append(next_state)
        new_path=path+[next_state]
        queue.append(new_path)

  return None

def moves(before,after):
  wolf_before=before[1]
  goat_before=before[2]
  cabbage_before=before[3]
  farmer_after=after[0]
  wolf_after=after[1]
  goat_after=after[2]
  cabbage_after=after[3]

  if farmer_after==1:
    direction="right"
  else:
    direction="left"

  if wolf_before != wolf_after:
    return "farmer crosses to the "+direction+" with wolf"
  elif goat_before != goat_after:
    return "farmer crosses to the "+direction+" with goat"
  elif cabbage_before != cabbage_after:
    return "farmer crosses to the "+ direction +" with cabbage"
  else:
    return "farmer crosses to the "+ direction + " alone."

def main():
  path=bfs(start,goal)
  if path is None:
    print("No solution found")
    return

  print("Each state is (farmer,wolf,goat,cabbage)")
  print("0 = left, 1 =  right ")
  print("")
  print("initial state: ", path[0])

  i=1
  while i<len(path):
    print("Step", i, ":", moves(path[i-1],path[i]), "-> new state", path[i])
    i+=1

  print("")
  print("total moves:",len(path)-1)




main()

missionaires=3
cannibals=3
start=(3,3,0,0,0)
goal=(0,0,1,3,3)

check=[(1,0),(2,0),(0,1),(0,2),(1,1)]

def safe(state):
  m_left=state[0]
  c_left=state[1]
  m_right=state[3]
  c_right=state[4]

  if m_left<0 or m_left > missionaires:
    return False
  if c_left<0 or c_left > cannibals:
    return False
  if m_right<0 or m_right > missionaires:
    return False
  if c_right<0 or c_right > cannibals:
    return False
  if m_left > 0 and m_left < c_left:
    return False
  if m_right > 0 and m_right < c_right:
    return False
  return True

def get_successors(state):
  m_left=state[0]
  c_left=state[1]
  boat=state[2]
  m_right=state[3]
  c_right=state[4]

  successors=[]

  for load in check:
    m=load[0]
    c=load[1]
    if boat==0:
      new_state=(m_left-m,c_left-c,1,m_right+m,c_right+c)
    else:
      new_state=(m_left+m,c_left+c,0,m_right-m,c_right-c)
    if safe(new_state):
      successors.append(new_state)
  return successors

def bfs(start,goal):
  queue=[[start]]
  visited=[start]

  while len(queue)>0:
    path=queue.pop(0)
    current=path[-1]

    if current==goal:
      return path

    successors= get_successors(current)
    for next_state in successors:
      if next_state not in visited:
        visited.append(next_state)
        new_path=path+[next_state]
        queue.append(new_path)

  return None

def moves(before, after):
  m_before=before[0]
  c_before=before[1]
  boat_before=before[2]
  m_after=after[0]
  c_after=after[1]

  if boat_before==0:
    m_moved=m_before-m_after
    c_moved=c_before-c_after
    direction = "right"

  else:
    m_moved=m_after-m_before
    c_moved=c_after-c_before
    direction = "left"

  text= "boat crosses to the "+direction+" with "
  if m_moved>0 and c_moved>0:
    text=text+str(m_moved)+" missionaries and "+str(c_moved)+" cannibals"
  elif m_moved>0:
    text=text+str(m_moved)+"missionaries"
  else:
    text=text+str(c_moved)+"cannibals"
  return text

def main():
  path=bfs(start,goal)
  if path is None:
    print("no solution found")
    return

  print("each state is (missionaries_left,cannibals_left,boat,missionaries_right,cannibals_right)")
  print("0 = left, 1 = right")
  print("")
  print("initial state: ", path[0])

  i=1
  while i < len(path):
    print("step",i,":",moves(path[i-1],path[i]),"-> new state",path[i])
    i+=1

  print("")
  print("total moves:",len(path)-1)

main()

import time

board = [[0] * 9 for _ in range(9)]


def leer_tablero(nombre_archivo):


    global board

    with open(nombre_archivo, "r") as f:
        lineas = [linea.strip() for linea in f if linea.strip() != ""]

    nuevo_tablero = [[0] * 9 for _ in range(9)]

    for i in range(9):
        linea = lineas[i]

        for j in range(9):
            c = linea[j]

            if c == "." or c == "0":
                nuevo_tablero[i][j] = 0
            else:
                nuevo_tablero[i][j] = int(c)

    board = nuevo_tablero





asignaciones = 0
backtracks = 0
profundidad_max = 0
total_soluciones = 0








def imprimir_tablero():
    for fila in board:
        print(" ".join(str(x) if x != 0 else "." for x in fila))


def reset_contadores():
    global asignaciones, backtracks, profundidad_max
    asignaciones = 0
    backtracks = 0
    profundidad_max = 0


def imprimir_stats(nombre, segundos):
    print("--- Estadisticas " + nombre + " ---")
    print("Asignaciones (estados generados):", asignaciones)
    print("Backtracks:", backtracks)
    print("Profundidad maxima de recursion:", profundidad_max)
    print("Tiempo de ejecucion (ms):", segundos * 1000)
    print()




def es_valido(fila, col, num):


    for k in range(9):
        if board[fila][k] == num:
            return False


    for k in range(9):
        if board[k][col] == num:
            return False


    fila_caja = (fila // 3) * 3
    col_caja = (col // 3) * 3

    for i in range(3):
        for j in range(3):
            if board[fila_caja + i][col_caja + j] == num:
                return False

    return True




def resolver_naive(profundidad=0):

    global asignaciones, backtracks, profundidad_max

    if profundidad > profundidad_max:
        profundidad_max = profundidad


    fila_libre = -1
    col_libre = -1

    for i in range(9):
        if fila_libre != -1:
            break

        for j in range(9):
            if board[i][j] == 0:
                fila_libre = i
                col_libre = j
                break


    if fila_libre == -1:
        return True


    for num in range(1, 10):

        if es_valido(fila_libre, col_libre, num):

            board[fila_libre][col_libre] = num
            asignaciones += 1

            if resolver_naive(profundidad + 1):
                return True


            board[fila_libre][col_libre] = 0
            backtracks += 1

    return False




def contar_soluciones():

    global total_soluciones


    fila_libre = -1
    col_libre = -1

    for i in range(9):
        if fila_libre != -1:
            break

        for j in range(9):
            if board[i][j] == 0:
                fila_libre = i
                col_libre = j
                break


    if fila_libre == -1:
        total_soluciones += 1
        return


    for num in range(1, 10):

        if es_valido(fila_libre, col_libre, num):

            board[fila_libre][col_libre] = num

            contar_soluciones()


            board[fila_libre][col_libre] = 0




def resolver_mrv(profundidad=0):

    global asignaciones, backtracks, profundidad_max

    if profundidad > profundidad_max:
        profundidad_max = profundidad


    mejor_fila = -1
    mejor_col = -1
    menor_cantidad = 10

    for i in range(9):
        for j in range(9):

            if board[i][j] == 0:

                cantidad = 0

                for num in range(1, 10):
                    if es_valido(i, j, num):
                        cantidad += 1

                if cantidad < menor_cantidad:
                    menor_cantidad = cantidad
                    mejor_fila = i
                    mejor_col = j


    if mejor_fila == -1:
        return True


    for num in range(1, 10):

        if es_valido(mejor_fila, mejor_col, num):

            board[mejor_fila][mejor_col] = num
            asignaciones += 1

            if resolver_mrv(profundidad + 1):
                return True


            board[mejor_fila][mejor_col] = 0
            backtracks += 1

    return False




def crear_dominios():

    dominio = [[set() for _ in range(9)] for _ in range(9)]

    for i in range(9):
        for j in range(9):

            if board[i][j] == 0:

                for num in range(1, 10):

                    if es_valido(i, j, num):
                        dominio[i][j].add(num)

    return dominio




def quitar_del_dominio(dominio, fila, col, num):



    cambiadas = []


    for k in range(9):

        if k != col and board[fila][k] == 0:
            if num in dominio[fila][k]:
                dominio[fila][k].remove(num)
                cambiadas.append((fila, k))


    for k in range(9):

        if k != fila and board[k][col] == 0:
            if num in dominio[k][col]:
                dominio[k][col].remove(num)
                cambiadas.append((k, col))


    fila_caja = (fila // 3) * 3
    col_caja = (col // 3) * 3

    for i in range(3):
        for j in range(3):

            fi = fila_caja + i
            cj = col_caja + j

            if (fi != fila or cj != col) and board[fi][cj] == 0:

                if num in dominio[fi][cj]:
                    dominio[fi][cj].remove(num)
                    cambiadas.append((fi, cj))

    return cambiadas




def tiene_dominio_vacio(dominio):

    for i in range(9):
        for j in range(9):

            if board[i][j] == 0 and len(dominio[i][j]) == 0:
                return True

    return False




def resolver_forward_checking(dominio, profundidad=0):

    global asignaciones, backtracks, profundidad_max

    if profundidad > profundidad_max:
        profundidad_max = profundidad


    mejor_fila = -1
    mejor_col = -1
    menor_cantidad = 10

    for i in range(9):
        for j in range(9):

            if board[i][j] == 0:

                cantidad = len(dominio[i][j])

                if cantidad < menor_cantidad:
                    menor_cantidad = cantidad
                    mejor_fila = i
                    mejor_col = j


    if mejor_fila == -1:
        return True


    for num in list(dominio[mejor_fila][mejor_col]):

        board[mejor_fila][mejor_col] = num
        asignaciones += 1


        cambiadas = quitar_del_dominio(
            dominio,
            mejor_fila,
            mejor_col,
            num
        )


        if not tiene_dominio_vacio(dominio):

            if resolver_forward_checking(
                dominio,
                profundidad + 1
            ):
                return True


        for fi, cj in cambiadas:
            dominio[fi][cj].add(num)


        board[mejor_fila][mejor_col] = 0
        backtracks += 1

    return False





def resolver_tablero(nombre_archivo):
    global total_soluciones

    print()
    print("============================================================")
    print("TABLERO:", nombre_archivo)
    print("============================================================")

    leer_tablero(nombre_archivo)

    print("Tablero inicial:")
    imprimir_tablero()
    print()


    leer_tablero(nombre_archivo)
    reset_contadores()

    t0 = time.time()
    ok = resolver_naive()
    t1 = time.time()

    print("Naive: resuelto =", ok)
    imprimir_tablero()
    imprimir_stats("Naive", t1 - t0)


    leer_tablero(nombre_archivo)
    reset_contadores()

    t0 = time.time()
    ok = resolver_mrv()
    t1 = time.time()

    print("MRV: resuelto =", ok)
    imprimir_tablero()
    imprimir_stats("MRV", t1 - t0)


    leer_tablero(nombre_archivo)
    reset_contadores()

    t0 = time.time()
    dominios = crear_dominios()
    ok = resolver_forward_checking(dominios)
    t1 = time.time()

    print("Forward Checking: resuelto =", ok)
    imprimir_tablero()
    imprimir_stats("Forward Checking", t1 - t0)


    leer_tablero(nombre_archivo)
    total_soluciones = 0

    contar_soluciones()

    print("Numero total de soluciones encontradas:", total_soluciones)
    print()





if __name__ == "__main__":
    resolver_tablero("board1.txt")
    resolver_tablero("board2.txt")

