# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AHSlCW9sLARwmMKOVnOEZBAzhJoxY4Dm
"""

# Comparacion de A* y Dijkstra
# Grafo tomado del ejemplo de Rumania (Russell & Norvig, cap 3.5)
# Los pesos de las aristas se obtienen de los valores g mostrados en la
# figura 3.18 (busqueda A* paso a paso). Los valores h son los de la
# figura 3.16 (distancia en linea recta hasta Bucarest).
# No se agregan ni cambian datos respecto al ejercicio del pdf.

grafo = {
    "Arad": {"Sibiu": 140, "Timisoara": 118, "Zerind": 75},
    "Sibiu": {"Arad": 140, "Fagaras": 99, "Oradea": 151, "Rimnicu Vilcea": 80},
    "Timisoara": {"Arad": 118},
    "Zerind": {"Arad": 75},
    "Fagaras": {"Sibiu": 99, "Bucharest": 211},
    "Oradea": {"Sibiu": 151},
    "Rimnicu Vilcea": {"Sibiu": 80, "Craiova": 146, "Pitesti": 97},
    "Craiova": {"Rimnicu Vilcea": 146, "Pitesti": 138},
    "Pitesti": {"Rimnicu Vilcea": 97, "Craiova": 138, "Bucharest": 101},
    "Bucharest": {"Fagaras": 211, "Pitesti": 101},
}

h_sld = {
    "Arad": 366,
    "Bucharest": 0,
    "Craiova": 160,
    "Fagaras": 176,
    "Oradea": 380,
    "Pitesti": 100,
    "Rimnicu Vilcea": 193,
    "Sibiu": 253,
    "Timisoara": 329,
    "Zerind": 374,
}


def nodo_de_menor_f(frontera, f):
    mejor = None
    for nodo in frontera:
        if mejor is None or f[nodo] < f[mejor]:
            mejor = nodo
    return mejor


def reconstruir_camino(padres, objetivo):
    camino = [objetivo]
    while padres[camino[-1]] is not None:
        camino.append(padres[camino[-1]])
    camino.reverse()
    return camino


def dijkstra(grafo, inicio, objetivo, mostrar_pasos=False):
    g = {nodo: float("inf") for nodo in grafo}
    g[inicio] = 0
    padres = {inicio: None}
    frontera = {inicio}
    visitados = set()
    nodos_expandidos = 0
    paso = 0

    while frontera:
        paso += 1
        if mostrar_pasos:
            opciones = [(nodo, g[nodo]) for nodo in frontera]
            print("paso", paso, "frontera:", opciones)

        actual = nodo_de_menor_f(frontera, g)
        frontera.remove(actual)

        if mostrar_pasos:
            print("  elige:", actual, "porque tiene el costo g mas bajo de la frontera")

        if actual == objetivo:
            return reconstruir_camino(padres, objetivo), g[objetivo], nodos_expandidos

        visitados.add(actual)
        nodos_expandidos += 1

        for vecino, costo in grafo[actual].items():
            if vecino in visitados:
                continue
            nuevo_costo = g[actual] + costo
            if nuevo_costo < g[vecino]:
                g[vecino] = nuevo_costo
                padres[vecino] = actual
                frontera.add(vecino)

    return None, float("inf"), nodos_expandidos


def a_estrella(grafo, heuristica, inicio, objetivo):
    g = {nodo: float("inf") for nodo in grafo}
    g[inicio] = 0
    f = {inicio: heuristica[inicio]}
    padres = {inicio: None}
    frontera = {inicio}
    visitados = set()
    nodos_expandidos = 0

    while frontera:
        actual = nodo_de_menor_f(frontera, f)
        frontera.remove(actual)

        if actual == objetivo:
            return reconstruir_camino(padres, objetivo), g[objetivo], nodos_expandidos

        visitados.add(actual)
        nodos_expandidos += 1

        for vecino, costo in grafo[actual].items():
            if vecino in visitados:
                continue
            nuevo_costo = g[actual] + costo
            if nuevo_costo < g[vecino]:
                g[vecino] = nuevo_costo
                padres[vecino] = actual
                f[vecino] = g[vecino] + heuristica[vecino]
                frontera.add(vecino)

    return None, float("inf"), nodos_expandidos


inicio = "Arad"
objetivo = "Bucharest"

camino_dij, costo_dij, exp_dij = dijkstra(grafo, inicio, objetivo)
camino_ae, costo_ae, exp_ae = a_estrella(grafo, h_sld, inicio, objetivo)

print("Dijkstra")
print("camino:", camino_dij)
print("costo:", costo_dij)
print("nodos expandidos:", exp_dij)
print()

print("A*")
print("camino:", camino_ae)
print("costo:", costo_ae)
print("nodos expandidos:", exp_ae)
print()

print("Conclusion")
print(
    f"Los dos algoritmos encuentran el mismo camino optimo con costo {costo_dij}, "
    f"pero Dijkstra expande {exp_dij} nodos y A* solo {exp_ae}. Dijkstra explora "
    "segun el costo acumulado g(n) sin saber hacia donde queda el objetivo, por eso "
    "revisa ciudades que no llevan a nada como Zerind, Timisoara, Oradea o Craiova. "
    "A* usa f(n) = g(n) + h(n), y como h_sld es admisible (nunca sobrestima la "
    "distancia real a Bucarest), prioriza los nodos que de verdad se acercan al "
    "objetivo. En complejidad ambos son O(V^2) en el peor caso con esta "
    "implementacion, pero para este problema A* es mejor porque llega al mismo "
    "resultado optimo explorando menos del grafo."
)