# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G2fJ946H37o_KjojtRWnq6EKyuV045ti
"""

# Isaac Espinosa
# 00342611
import random
import matplotlib.pyplot as plt

# Parameters
POPULATION_SIZE = 100
BITS = 16
EPOCHS = 100
K = 10
MUTATION_RATE = 0.1


def bits_to_number(individual, start, end):
    sign = -1 if individual[start] == 1 else 1
    value = 0
    for i in range(start + 1, end):
        value = value * 2 + individual[i]
    return sign * value


def fitness(individual):
    x = bits_to_number(individual, 0, 8)
    y = bits_to_number(individual, 8, 16)
    return (x + 2)**2 + (y - 2)**2 + 10


def generate_individual():
    return [random.randint(0, 1) for _ in range(BITS)]


def generate_population():
    return [generate_individual() for _ in range(POPULATION_SIZE)]


def selection(population):
    population.sort(key=fitness)
    return population[:K]


def crossover(parent1, parent2):
    point = random.randint(1, BITS - 1)
    child1 = parent1[:point] + parent2[point:]
    child2 = parent2[:point] + parent1[point:]
    return child1, child2


def mutation(individual):
    for i in range(BITS):
        if random.random() < MUTATION_RATE:
            individual[i] = 1 - individual[i]
    return individual


def genetic_algorithm():
    population = generate_population()
    best_fitness_history = []

    for epoch in range(EPOCHS):
        selected = selection(population)

        # Elitism
        new_population = [ind[:] for ind in selected]

        while len(new_population) < POPULATION_SIZE:
            parent1 = random.choice(selected)
            parent2 = random.choice(selected)

            child1, child2 = crossover(parent1, parent2)

            child1 = mutation(child1)
            child2 = mutation(child2)

            new_population.append(child1)
            if len(new_population) < POPULATION_SIZE:
                new_population.append(child2)

        population = new_population

        best = min(population, key=fitness)
        best_fitness_history.append(fitness(best))

        x = bits_to_number(best, 0, 8)
        y = bits_to_number(best, 8, 16)
        bit_str = "".join(map(str, best))

        # Output each individual epoch clearly
        print(
            f"Epoch {epoch + 1:3d} | Bits: {bit_str} | Best x: {x:4d} | Best y: {y:4d} | Fitness: {fitness(best)}"
        )

    return min(population, key=fitness), best_fitness_history


best_solution, best_fitness_history = genetic_algorithm()

x = bits_to_number(best_solution, 0, 8)
y = bits_to_number(best_solution, 8, 16)
bit_str = "".join(map(str, best_solution))

print("\n" + "=" * 50)
print("FINAL SOLUTION FOUND:")
print(f"Bit String: {bit_str}")
print(f"x: {x}")
print(f"y: {y}")
print(f"Min Fitness f(x, y): {fitness(best_solution)}")
print("=" * 50)

plt.figure(figsize=(10, 5))
plt.plot(range(1, EPOCHS + 1), best_fitness_history)


plt.xticks(range(0, EPOCHS + 1, 5))


plt.grid(True)

plt.xlabel("Epoch")
plt.ylabel("f(best solution)")
plt.title("Genetic Algorithm")
plt.show()