# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ti_AiP_5LWHQl_Yb3r6JYW-k7wIoytdF
"""

# Isaac Espinosa 00342611
# Swarm algorithm (PSO)
import numpy as np

#genetic algorithm function
def f(x):
    return (x[0] + 2)**2 + (x[1] - 2)**2 + 10



def swalgorithm(N, D, bounds, max_iter):
    w = 0.5
    a1 = 1
    a2 = 1

    lower, upper = bounds

    # Set t <- 0
    t = 0

    # Initialize S and set P = S
    S = np.random.uniform(lower, upper, (N, D))
    V = np.zeros((N, D))
    P = np.copy(S)

    # Evaluate S and P, and define index g of the best position
    f_S = np.apply_along_axis(f, 1, S)
    f_P = np.copy(f_S)
    g = np.argmin(f_P)

    # while termination criterion not met
    while t < max_iter:
        # Update S
        phi_1 = np.random.rand(N, D)
        phi_2 = np.random.rand(N, D)
        V = w * V + a1 * phi_1 * (P - S) + a2 * phi_2 * (P[g] - S)
        S = np.clip(S + V, lower, upper)

        # Evaluate S
        f_S = np.apply_along_axis(f, 1, S)

        # Update P and redefine index g
        improved = f_S < f_P
        P[improved] = S[improved]
        f_P[improved] = f_S[improved]
        g = np.argmin(f_P)

        # Set t <- t + 1
        t += 1

    # Return P_g
    return P[g], f_P[g]


P_g, f_g = swalgorithm(N=20, D=2, bounds=(-10, 10), max_iter=100)
print("Best x:", P_g)
print("f(x):", f_g)