# -*- coding: utf-8 -*-
"""tic-tac-toe_4x4_Isaac.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tzgw4p5hdG4uxM8Vgp7FuJtVtZqb5cgO
"""

# Isaac Espinosa
# Codigo banner: 00342611

# Max depth of 4 with a simple heuristic, because full minimax is too large

MAX_PROFUNDIDAD = 4


def mostrar_tablero(tablero):
    print()
    for fila in range(4):
        inicio = fila * 4
        casillas = tablero[inicio:inicio + 4]
        print(" " + " | ".join(casillas) + " ")
        if fila < 3:
            print("----+----+----+----")
    print()


def hay_ganador(tablero):
    combinaciones = [
        (0, 1, 2, 3), (4, 5, 6, 7), (8, 9, 10, 11), (12, 13, 14, 15),
        (0, 4, 8, 12), (1, 5, 9, 13), (2, 6, 10, 14), (3, 7, 11, 15),
        (0, 5, 10, 15), (3, 6, 9, 12)
    ]

    for (a, b, c, d) in combinaciones:
        if tablero[a] == tablero[b] == tablero[c] == tablero[d] and tablero[a] != ' ':
            return tablero[a]
    return None


def tablero_lleno(tablero):
    return ' ' not in tablero


def evaluar(tablero):
    ganador = hay_ganador(tablero)
    if ganador == 'X':
        return +1
    elif ganador == 'O':
        return -1
    else:
        return 0


def evaluar_heuristica(tablero):
    combinaciones = [
        (0, 1, 2, 3), (4, 5, 6, 7), (8, 9, 10, 11), (12, 13, 14, 15),
        (0, 4, 8, 12), (1, 5, 9, 13), (2, 6, 10, 14), (3, 7, 11, 15),
        (0, 5, 10, 15), (3, 6, 9, 12)
    ]

    puntaje = 0
    for combo in combinaciones:
        valores = [tablero[i] for i in combo]
        tiene_x = 'X' in valores
        tiene_o = 'O' in valores

        if tiene_x and not tiene_o:
            puntaje += valores.count('X')
        elif tiene_o and not tiene_x:
            puntaje -= valores.count('O')

    return puntaje


def movimientos_disponibles(tablero):
    return [i for i, casilla in enumerate(tablero) if casilla == ' ']


def minimax(tablero, es_turno_de_X, profundidad):
    puntaje = evaluar(tablero)
    if puntaje == 1:
        return (puntaje, None)
    if puntaje == -1:
        return (puntaje, None)
    if tablero_lleno(tablero):
        return (0, None)

    if profundidad == 0:
        return (evaluar_heuristica(tablero), None)

    moves = movimientos_disponibles(tablero)

    if es_turno_de_X:
        mejor_valor = float('-inf')
        mejor_movimiento = None
        for move in moves:
            tablero[move] = 'X'
            valor, _ = minimax(tablero, False, profundidad - 1)
            tablero[move] = ' '

            if valor > mejor_valor:
                mejor_valor = valor
                mejor_movimiento = move
        return (mejor_valor, mejor_movimiento)
    else:
        mejor_valor = float('inf')
        mejor_movimiento = None
        for move in moves:
            tablero[move] = 'O'
            valor, _ = minimax(tablero, True, profundidad - 1)
            tablero[move] = ' '

            if valor < mejor_valor:
                mejor_valor = valor
                mejor_movimiento = move
        return (mejor_valor, mejor_movimiento)


def jugar():
    tablero = [' '] * 16
    turno = 'O'

    while True:
        mostrar_tablero(tablero)

        ganador = hay_ganador(tablero)
        if ganador == 'X':
            print("¡La IA (X) ha ganado!")
            break
        elif ganador == 'O':
            print("¡Felicidades, has ganado!")
            break
        elif tablero_lleno(tablero):
            print("¡Es un empate!")
            break

        if turno == 'O':
            try:
                movimiento = int(input("Elige una casilla (1-16): ")) - 1
            except ValueError:
                print("Entrada no válida. Inténtalo de nuevo.")
                continue

            if movimiento < 0 or movimiento > 15 or tablero[movimiento] != ' ':
                print("Movimiento inválido. Inténtalo de nuevo.")
                continue

            tablero[movimiento] = 'O'
            turno = 'X'
        else:
            print("La IA está pensando...")
            _, mejor_mov = minimax(tablero, True, MAX_PROFUNDIDAD)
            tablero[mejor_mov] = 'X'
            turno = 'O'


if __name__ == "__main__":
    jugar()