#!/usr/bin/env python3
"""Generate study material from the wiki (run after any wiki change).

Usage:
    python3 tools/build_study.py

Writes:
  wiki/study/intuitive-pseudocode.md   every "Pseudocódigo intuitivo" section,
                                       in the order of wiki/index.md
  study-tools/web/quiz.html            interactive quiz (questions from wiki/study/quiz-bank.md)
  study-tools/anki/ia-wiki-flashcards.txt
                                       Anki deck (tab-separated, HTML) built from the
                                       glossary, exam questions, practice problems and
                                       pseudocode sections
Generated files carry a "do not edit" banner: edit the wiki pages instead.
"""
import html
import json
import re
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WIKI = ROOT / "wiki"
PSEUDO_HEADING = "## Pseudocódigo intuitivo (para explicar en el examen)"


def concept_order():
    """Concept pages in the order they appear in index.md, grouped by unit."""
    index = (WIKI / "index.md").read_text(encoding="utf-8")
    section = index.split("## Concepts", 1)[1].split("\n## ", 1)[0]
    units, current = [], None
    for line in section.splitlines():
        unit = re.match(r"\*\*(.+?)\*\*", line)
        if unit:
            current = (unit.group(1), [])
            units.append(current)
            continue
        link = re.search(r"\]\((concepts/[^)]+\.md)\)", line)
        if link and current:
            current[1].append(WIKI / link.group(1))
    return units


def title_of(page):
    m = re.search(r"^# (.+)$", page.read_text(encoding="utf-8"), flags=re.M)
    return m.group(1).strip() if m else page.stem


def section_of(page, heading):
    text = page.read_text(encoding="utf-8")
    if heading not in text:
        return None
    body = text.split(heading, 1)[1]
    return re.split(r"\n## ", body, maxsplit=1)[0].strip()


def build_pseudocode():
    out = [
        "---",
        "title: Intuitive pseudocode cheat sheet",
        "type: study",
        "tags: [study, pseudocode, cheat-sheet, generated]",
        "sources: [book-russell-norvig-aima, book-eiben-smith-evolutionary-computing, slides-02-problem-solving, slides-04-optimization, slides-xx-logic-programming-prolog]",
        f"updated: {date.today().isoformat()}",
        "---",
        "# Intuitive pseudocode cheat sheet (Pseudocódigo intuitivo — todo en una página)",
        "",
        "> **Summary (EN):** Every algorithm of the course as plain-English steps you can reproduce in the test, "
        "with a one-line Spanish idea and a short \"say it in the exam\" answer. Generated by `tools/build_study.py` "
        "from the concept pages — **do not edit here**; edit the concept page and rebuild.",
        "",
        "**Cómo estudiar con esta hoja:** tapa el bloque de pasos, lee solo la *Idea*, y escribe los pasos en inglés de memoria. "
        "Luego compara. Repite con los que fallaste.",
        "",
    ]
    count = 0
    for unit, pages in concept_order():
        blocks = []
        for page in pages:
            body = section_of(page, PSEUDO_HEADING)
            if body:
                blocks.append(f"### [{title_of(page)}](../concepts/{page.name})\n\n{body}\n")
                count += 1
        if blocks:
            out.append(f"## {unit}\n")
            out.extend(blocks)
    target = WIKI / "study" / "intuitive-pseudocode.md"
    target.write_text("\n".join(out).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {target.relative_to(ROOT)} ({count} algorithms)")


UNIT_TAGS = {"1": "unit1-agents", "2": "unit2-search", "3": "unit3-logic", "4": "unit4-optimization"}


def md_to_html(text):
    """Small markdown → HTML converter, enough for Anki cards."""
    text = re.sub(r"```mermaid.*?```", "<i>(diagram: see the wiki page)</i>", text, flags=re.S)
    blocks, out = re.split(r"(```.*?```)", text, flags=re.S), []
    for block in blocks:
        if block.startswith("```"):
            code = re.sub(r"^```\w*\n?|```$", "", block)
            out.append("<pre>" + html.escape(code.rstrip()) + "</pre>")
            continue
        b = html.escape(block)
        b = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", b)
        b = re.sub(r"(?<![\w*])\*(?!\s)(.+?)\*(?!\w)", r"<i>\1</i>", b)
        b = re.sub(r"`([^`]+)`", r"<code>\1</code>", b)
        b = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", b)        # drop link targets
        b = b.replace("\\*", "*").replace("\\_", "_").replace("\\|", "|")
        out.append(b.strip().replace("\n", "<br>"))
    return "<br>".join(x for x in out if x)


def cards_from_glossary():
    text = (WIKI / "glossary.md").read_text(encoding="utf-8")
    for line in text.splitlines():
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) == 4 and cells[0] not in ("English", "---") and not set(cells[0]) <= {"-"}:
            front = md_to_html(cells[0])
            back = f"<b>{md_to_html(cells[1])}</b><br>{md_to_html(cells[2])}"
            yield front, back, "glossary"


def cards_from_details(path, default_tag):
    """<details><summary>Q</summary> A </details> blocks; unit taken from the nearest heading."""
    text = path.read_text(encoding="utf-8")
    unit_tag = default_tag
    for part in re.split(r"(?m)^(## .+)$", text):
        if part.startswith("## "):
            m = re.search(r"Unidad (\d)", part)
            if m:
                unit_tag = UNIT_TAGS.get(m.group(1), default_tag)
            current_heading = part[3:].strip()
            continue
        for q, a in re.findall(r"<details><summary>(.*?)</summary>(.*?)</details>", part, flags=re.S):
            yield md_to_html(q.strip()), md_to_html(a.strip()), unit_tag


def cards_from_practice(path, tag):
    """Each '## Problem n — title' section: statement → solution."""
    text = path.read_text(encoding="utf-8")
    for sec in re.split(r"(?m)^## ", text)[1:]:
        if not sec.startswith("Problem"):
            continue
        title, body = sec.split("\n", 1)
        m = re.search(r"<details><summary>.*?</summary>(.*?)</details>", body, flags=re.S)
        if not m:
            continue
        statement = body[: m.start()].strip()
        yield (f"<b>{html.escape(title.strip())}</b><br>" + md_to_html(statement),
               md_to_html(m.group(1).strip()), tag + " practice")


def cards_from_pseudocode():
    for unit, pages in concept_order():
        m = re.match(r"Unit (\d)", unit)
        tag = UNIT_TAGS.get(m.group(1), "general") if m else "general"
        for page in pages:
            body = section_of(page, PSEUDO_HEADING)
            if not body:
                continue
            idea = re.search(r"\*\*Idea \(ES\):\*\*(.+)", body)
            steps = re.search(r"```text\n(.*?)```", body, flags=re.S)
            say = re.search(r"\*\*Say it in the exam \(EN\):\*\*(.+)", body)
            front = (f"Write the intuitive pseudocode: <b>{html.escape(title_of(page))}</b>"
                     + (f"<br><i>Idea: {md_to_html(idea.group(1).strip())}</i>" if idea else ""))
            back = ("<pre>" + html.escape(steps.group(1).rstrip()) + "</pre>" if steps else "")
            if say:
                back += "<br>" + md_to_html(say.group(1).strip())
            yield front, back, tag + " pseudocode"


def parse_quiz_bank():
    """### unitN | question / - [ ] / - [x] / > explanation / see: page"""
    text = (WIKI / "study" / "quiz-bank.md").read_text(encoding="utf-8")
    questions = []
    for block in re.split(r"(?m)^### ", text)[1:]:
        lines = block.strip().splitlines()
        unit, question = [x.strip() for x in lines[0].split("|", 1)]
        options, correct, explanation, see = [], None, "", ""
        for line in lines[1:]:
            m = re.match(r"- \[( |x)\] (.+)", line.strip())
            if m:
                if m.group(1) == "x":
                    correct = len(options)
                options.append(m.group(2).strip())
            elif line.startswith(">"):
                explanation += line.lstrip("> ").strip() + " "
            elif line.startswith("see:"):
                see = line[4:].strip()
            elif line.startswith("## "):
                break
        if correct is None or len(options) < 2:
            raise SystemExit(f"quiz-bank: bad question block: {lines[0]}")
        clean = lambda t: t.replace("\\*", "*").replace("`", "")
        questions.append({"id": f"{unit}-{len(questions)}", "unit": unit, "question": clean(question),
                          "options": [clean(o) for o in options], "correct": correct,
                          "explanation": clean(explanation.strip()), "see": see})
    return questions


def build_quiz():
    questions = parse_quiz_bank()
    tpl = (ROOT / "study-tools" / "web" / "quiz.template.html").read_text(encoding="utf-8")
    data = json.dumps(questions, ensure_ascii=False).replace("</", "<\\/")
    out = tpl.replace("/*QUIZ_DATA*/", data)
    target = ROOT / "study-tools" / "web" / "quiz.html"
    target.write_text("<!-- GENERATED by tools/build_study.py from wiki/study/quiz-bank.md — edit those, not this file. -->\n" + out, encoding="utf-8")
    print(f"wrote {target.relative_to(ROOT)} ({len(questions)} questions)")
    return questions


def cards_from_quiz(questions):
    for q in questions:
        front = html.escape(q["question"]) + "<br>" + "<br>".join(
            f"{chr(65 + i)}. {html.escape(o)}" for i, o in enumerate(q["options"]))
        back = f"<b>{chr(65 + q['correct'])}. {html.escape(q['options'][q['correct']])}</b><br>{html.escape(q['explanation'])}"
        yield front, back, UNIT_TAGS.get(q["unit"][-1], q["unit"]) + " quiz"


def build_anki(quiz_questions=()):
    cards = list(cards_from_glossary())
    cards += list(cards_from_details(WIKI / "study" / "exam-questions.md", "exam"))
    for n, tag in [("1-agents", "unit1-agents"), ("2-search", "unit2-search"),
                   ("3-logic", "unit3-logic"), ("4-optimization", "unit4-optimization")]:
        cards += list(cards_from_practice(WIKI / "study" / f"practice-unit-{n}.md", tag))
    cards += list(cards_from_pseudocode())
    cards += list(cards_from_quiz(quiz_questions))
    out_dir = ROOT / "study-tools" / "anki"
    out_dir.mkdir(parents=True, exist_ok=True)
    lines = ["#separator:tab", "#html:true", "#deck:Inteligencia Artificial (LLM Wiki)",
             "#notetype:Basic", "#tags column:3"]
    for front, back, tags in cards:
        clean = lambda x: x.replace("\t", " ").replace("\n", "<br>")
        lines.append(f"{clean(front)}\t{clean(back)}\t{tags}")
    target = out_dir / "ia-wiki-flashcards.txt"
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    counts = {}
    for _, _, tags in cards:
        for t in tags.split():
            counts[t] = counts.get(t, 0) + 1
    print(f"wrote {target.relative_to(ROOT)} ({len(cards)} cards: {counts})")
    return len(cards), counts


if __name__ == "__main__":
    build_pseudocode()
    build_anki(build_quiz())
