#!/usr/bin/env python3
"""Generate study material from the wiki (run after any wiki change).

Usage:
    python3 tools/build_study.py

Writes:
  wiki/study/intuitive-pseudocode.md   every "Pseudocódigo intuitivo" section,
                                       in the order of wiki/index.md
Generated files carry a "do not edit" banner: edit the concept pages instead.
"""
import re
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WIKI = ROOT / "wiki"
PSEUDO_HEADING = "## Pseudocódigo intuitivo (para explicar en el examen)"


def concept_order():
    """Concept pages in the order they appear in index.md, grouped by unit."""
    index = (WIKI / "index.md").read_text(encoding="utf-8")
    section = index.split("## Concepts", 1)[1].split("\n## ", 1)[0]
    units, current = [], None
    for line in section.splitlines():
        unit = re.match(r"\*\*(.+?)\*\*", line)
        if unit:
            current = (unit.group(1), [])
            units.append(current)
            continue
        link = re.search(r"\]\((concepts/[^)]+\.md)\)", line)
        if link and current:
            current[1].append(WIKI / link.group(1))
    return units


def title_of(page):
    m = re.search(r"^# (.+)$", page.read_text(encoding="utf-8"), flags=re.M)
    return m.group(1).strip() if m else page.stem


def section_of(page, heading):
    text = page.read_text(encoding="utf-8")
    if heading not in text:
        return None
    body = text.split(heading, 1)[1]
    return re.split(r"\n## ", body, maxsplit=1)[0].strip()


def build_pseudocode():
    out = [
        "---",
        "title: Intuitive pseudocode cheat sheet",
        "type: study",
        "tags: [study, pseudocode, cheat-sheet, generated]",
        "sources: [book-russell-norvig-aima, book-eiben-smith-evolutionary-computing, slides-02-problem-solving, slides-04-optimization, slides-xx-logic-programming-prolog]",
        f"updated: {date.today().isoformat()}",
        "---",
        "# Intuitive pseudocode cheat sheet (Pseudocódigo intuitivo — todo en una página)",
        "",
        "> **Summary (EN):** Every algorithm of the course as plain-English steps you can reproduce in the test, "
        "with a one-line Spanish idea and a short \"say it in the exam\" answer. Generated by `tools/build_study.py` "
        "from the concept pages — **do not edit here**; edit the concept page and rebuild.",
        "",
        "**Cómo estudiar con esta hoja:** tapa el bloque de pasos, lee solo la *Idea*, y escribe los pasos en inglés de memoria. "
        "Luego compara. Repite con los que fallaste.",
        "",
    ]
    count = 0
    for unit, pages in concept_order():
        blocks = []
        for page in pages:
            body = section_of(page, PSEUDO_HEADING)
            if body:
                blocks.append(f"### [{title_of(page)}](../concepts/{page.name})\n\n{body}\n")
                count += 1
        if blocks:
            out.append(f"## {unit}\n")
            out.extend(blocks)
    target = WIKI / "study" / "intuitive-pseudocode.md"
    target.write_text("\n".join(out).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {target.relative_to(ROOT)} ({count} algorithms)")


if __name__ == "__main__":
    build_pseudocode()
